### ISSUE TITLE
成立fsn.dev开源社区提案FDIP-0001

### ISSUE THREAD

**Issue by zhaojun-sh** [fsn-dev/FDIPs#1]
# 成立fsn.dev开源社区提案
fsn.dev开源社区欢迎开发者、研究者、极客、设计师、内容创造者、产品经理、翻译者、推广运营者等加入，参与社区开源项目、产品设计、文章翻译、社区提案等任务，同时组织编程比赛、线下meetup、AMA、黑客松、开发者大会、区域节点等活动。共同建设自由与创新的fsn.dev开源社区。

## 激励计划
FUSION基金会设立100万个FSN的开源社区支持计划，支持fsn.dev开源社区建设与可持续发展。 

fsn.dev开源社区将立即启动社区任务与活动激励，加入社区即可赢取1000个FSN，推荐成功即可赢取200个FSN，参与编程开发赢取共35万个FSN，参与社区活动还可以赢取更多奖励！ 

注：以上奖励为FSN使用权可用于挖矿等。 

## 开源社区成员角色
1、内容创造者：内容写作、编辑、在线文档
2、设计师：UI、logo、海报、视频、宣传材料
3、开发者：APP、网页、后端等代码开发、测试、发布
4、研究者：研究分享技术内容
5、极客：FSN公链和应用的深度使用及创意等
6、翻译者：内容翻译
7、运维管理：网站、服务器、发布等
8、社群大使：活动组织、服务支持、传播与沟通
9、社区用户：参与社区，使用FSN公链和应用等

## 预算规划
1、开源社区人数积累 10万个FSN 
- 新加入1000个3个月，推荐200个3个月

2、开发奖励 35万个FSN
- SDK奖励 2万个一年 3种语言共6万个
- 移动钱包奖励 10万个一年
- OTC等应用 5万个一年
- DEX交易所等 5万个一年
- 去中心化借贷等 5万个一年
- 社区提案项目 4万个一年

3、任务奖励 25万个FSN
- 活动、翻译、文章、设计、找BUG等

4、节点挖矿 20万个FSN
- 北上深杭 区域节点 

5、10万个FSN预留 
- 社区运营成本及参与贡献奖励

## 行动计划
1、发布支持计划公告。制定1000个社区成员的目标。 

2、发布注册流程：国内、金数据小程序；国外：google form  

3、发布社区成员扩张奖励方案。  注册通过奖励1000个FSN3个月挖矿权，推荐一个奖励200个FSN3个月挖矿权。内部推荐可以获得400个奖励。 

4、发布推广海报，打call海报。

5、发布审核标准，进行注册审核。必须是真实身份，防止羊毛党。  

6、建立开源社区微信群，持续沟通与发布信息。 

7、建立github开源社区组织，注册通过者必须加入，加入后可以参与社区任务与活动。 

8、组织线下meetup，沟通与推广。   

9、发布SDK编程项目、开源社区logo设计、文章翻译等第一批任务。 

10、持续3个月左右，每周统计状态，及时调整方案。 

## 注册流程
中文社区通过微信小程序注册，英文社区通过google form注册，注册流程分三个步骤：
1. 填写注册信息，提供github账号；
2. 中文社区加入微信群，英文社区加入telegram开发群；
3. 加入github.com/fsn-dev社区公开会员。

## 审核标准
虚假账号与材料无法通过审核，注册信息要求真实有效：
1、注册的github账号要求：账号需要注册时间半年以上，如果是翻译、设计等角色可以是新注册github账号
2、注册的相关技能说明要求：可以是简历附件、参与github开源项目、linkedin地址、设计文件、翻译文章、自媒体等其中一种
3、加入社群要求：中文社区加入开源社区微信群，英文社区加入telegram开发群，审核通过后加入github.com/fsn-dev组织成为社区公开会员。

用户注册信息仅用于社区注册。
本次活动最终解释权归fsn.dev开源社区所有。

**Comment by zhaojun-sh** [comment]
1、发布支持计划。制定1000个社区成员的目标。 

2、发布注册流程：国内、金数据小程序；国外：google form  

3、发布社区成员扩张奖励方案。  注册通过奖励1000个FSN3个月挖矿权，推荐一个奖励200个FSN3个月挖矿权。内部推荐可以获得400个奖励。 

4、发布推广海报，打call海报。

5、发布审核标准，进行注册审核。必须是真实身份，防止羊毛党。  

6、建立开源社区微信群，持续沟通与发布信息。 

7、建立github开源社区组织，注册通过者必须加入，加入后可以参与社区任务与活动。 

8、组织线下meetup，沟通与推广。   

9、发布SDK编程项目、开源社区logo设计、文章翻译等第一批任务。 

10、持续3个月左右，每周统计状态，及时调整方案。

**Comment by zhaojun-sh** [comment]
## 审核标准
加入社区需要提供：
1、github账号
2、相关经验说明(可以是github开源项目、linkedin地址、简历、设计文件、翻译文章、自媒体等其中一种)

申请通过后加入github.com/fsn-dev组织和微信群，成为社区成员。

注：虚假账号与材料无法通过审核。

**Comment by zhaojun-sh** [comment]
开源社区成员角色：
1、内容创造者：内容写作、编辑、在线文档
2、设计师：UI、logo、海报、视频、宣传材料
3、开发者：APP、网页、后端等代码开发、测试、发布
4、研究者：研究分享技术内容
5、翻译者：内容翻译
6、运维管理：网站、服务器、发布等
7、社群大使：活动组织、服务支持、传播与沟通

**Comment by KenianShi** [comment]
can i be the first one to take part in the event,haha... the event sounds very greate

**Comment by zhaojun-sh** [comment]
加微信号july225进群 备注 fsn.dev开源社区
